-- ============================================================
-- schema.sql
-- Supabase / PostgreSQL - fintech-automation database schema
-- Tables: transactions, audit_log, approval_log, event_queue
-- Last updated: reflects actual production schema
-- ============================================================

-- ============================================================
-- 1. transactions
-- Core ledger: every financial event (payment, transfer, refund,
-- withdrawal) creates one row here.
-- Status lifecycle: pending -> approved | rejected | processing
-- ============================================================
CREATE TABLE IF NOT EXISTS transactions (
  id               SERIAL         PRIMARY KEY,
  user_id          INT            NOT NULL,
  amount           NUMERIC(18,2)  NOT NULL,
  type             VARCHAR(50),                         -- payment | transfer | refund | withdrawal
  status           VARCHAR(50)    DEFAULT 'pending',   -- pending | approved | rejected | processing
  created_at       TIMESTAMP      DEFAULT NOW(),
  approved_by      VARCHAR(100),
  approved_at      TIMESTAMP,
  rejection_reason TEXT,
  updated_at       TIMESTAMPTZ    DEFAULT NOW()
);

COMMENT ON TABLE  transactions                  IS 'Core financial transaction ledger';
COMMENT ON COLUMN transactions.type             IS 'payment | transfer | refund | withdrawal';
COMMENT ON COLUMN transactions.status           IS 'pending | approved | rejected | processing';
COMMENT ON COLUMN transactions.rejection_reason IS 'Set by n8n or Retool on manual/auto rejection';

-- ============================================================
-- 2. audit_log
-- Immutable compliance trail: every status change, approval,
-- rejection, or flag creates one row here.
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_log (
  id             SERIAL       PRIMARY KEY,
  action         VARCHAR(100) NOT NULL,   -- Transaction Approved | Transaction Rejected | Transaction Flagged
  transaction_id INT          REFERENCES transactions(id) ON DELETE SET NULL,
  performed_by   VARCHAR(200),            -- email of the operator or system actor
  details        TEXT,                    -- human-readable description
  created_at     TIMESTAMP    DEFAULT NOW()
);

COMMENT ON TABLE  audit_log                IS 'Immutable compliance and operations audit trail';
COMMENT ON COLUMN audit_log.action         IS 'Transaction Approved | Transaction Rejected | Transaction Flagged';
COMMENT ON COLUMN audit_log.performed_by   IS 'Email of the human operator or n8n system actor';

-- ============================================================
-- 3. approval_log
-- Records every approval decision (auto or manual) for a
-- transaction. Linked to the approval workflow in n8n.
-- ============================================================
CREATE TABLE IF NOT EXISTS approval_log (
  id           SERIAL         PRIMARY KEY,
  approval_id  VARCHAR(100)   UNIQUE NOT NULL,  -- UUID generated by n8n approval workflow
  user_id      INT            REFERENCES transactions(id) ON DELETE CASCADE,
  amount       NUMERIC(18,2),
  status       VARCHAR(50)    DEFAULT 'pending',  -- pending | approved | rejected
  decided_at   TIMESTAMP,
  created_at   TIMESTAMP      DEFAULT NOW()
);

COMMENT ON TABLE  approval_log             IS 'Approval decisions from manual manager review workflow';
COMMENT ON COLUMN approval_log.approval_id IS 'Unique ID generated by n8n Generate Approval ID node';
COMMENT ON COLUMN approval_log.status      IS 'pending | approved | rejected';
COMMENT ON COLUMN approval_log.decided_at  IS 'Timestamp when manager clicked approve/reject link';

-- ============================================================
-- 4. event_queue
-- Decoupled async processing buffer. Incoming webhooks create
-- rows here; the transaction processor polls and processes them.
-- ============================================================
CREATE TABLE IF NOT EXISTS event_queue (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type    TEXT        NOT NULL,    -- payment | transfer | refund | withdrawal
  payload       JSONB       NOT NULL,
  status        TEXT        DEFAULT 'pending',   -- pending | processing | done | failed
  priority      INT         DEFAULT 1,           -- 1=low, 2=medium, 3=high, 5=urgent
  retry_count   INT         DEFAULT 0,
  error_message TEXT,
  received_at   TIMESTAMPTZ DEFAULT NOW(),
  processed_at  TIMESTAMPTZ,
  created_by    TEXT                             -- source system or webhook identifier
);

COMMENT ON TABLE  event_queue              IS 'Async event buffer - polled by n8n transaction processor';
COMMENT ON COLUMN event_queue.event_type   IS 'payment | transfer | refund | withdrawal';
COMMENT ON COLUMN event_queue.status       IS 'pending | processing | done | failed';
COMMENT ON COLUMN event_queue.priority     IS '1=low, 2=medium, 3=high, 5=urgent (higher = processed first)';
COMMENT ON COLUMN event_queue.retry_count  IS 'Incremented on failure; events with retry_count>=3 are dead-lettered';
COMMENT ON COLUMN event_queue.created_by   IS 'Webhook source identifier or system actor';

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE transactions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_log  ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_queue   ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "service_all_transactions"  ON transactions  FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_all_audit_log"     ON audit_log     FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_all_approval_log" ON approval_log  FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_all_event_queue"  ON event_queue   FOR ALL USING (auth.role() = 'service_role');

-- Authenticated users can read their own transactions
CREATE POLICY "users_read_own_transactions"
  ON transactions FOR SELECT
  USING (auth.uid()::text = user_id::text);

-- Authenticated users can read audit logs for their own transactions
CREATE POLICY "users_read_own_audit_log"
  ON audit_log FOR SELECT
  USING (
    transaction_id IN (
      SELECT id FROM transactions WHERE user_id = auth.uid()::int
    )
  );
